version: "2"
services:
  build:
    image: docker.isaacscience.org/isaac-cs-builder
    build:
      context: .
      dockerfile: Dockerfile-Builder
    cpu_shares: 100 # Never use more than ~10% CPU when under heavy load
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "~/.docker/config.json:/root/.docker/config.json:ro"
      - "./build.sh:/build.sh:ro"
    network_mode: bridge
    environment:
      UPDATE_API_DEPS: ${UPDATE_API_DEPS}
networks:
  default:
    external:
      name: bridge
