#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "Usage: compose-live VERSION"
    exit 1
fi

# Arg: app version

APP_VERSION=$1
ENV=live
# We're done with the first argument. The remainder will be passed to docker-compose
shift 1


# Pull the correct App image, inspect it to find the required API version, pull that.

if [ $1 = "create" ] || [ $1 = "exec" ] || [ $1 = "pull" ] || [ $1 = "push" ] || [ $1 = "run" ] || [ $1 = "start" ] || [ $1 = "up" ]; then
  docker pull docker.isaacscience.org/isaac-cs-app:$APP_VERSION
  API_VERSION=`docker inspect -f '{{.Config.Labels.apiVersion}}' docker.isaacscience.org/isaac-cs-app:$APP_VERSION`
  docker pull docker.isaacscience.org/isaac-api:$API_VERSION
else
  API_VERSION=`docker inspect -f '{{.Config.Labels.apiVersion}}' docker.isaacscience.org/isaac-cs-app:$APP_VERSION`
fi

API_NAME=cs-api-$ENV-$API_VERSION
APP_NAME=cs-app-$ENV-$APP_VERSION

PG=cs-pg-live
CONTENT=live

cat << EOF | docker-compose -p dc-$APP_NAME -f - $@
version: '2'
services:
  $APP_NAME:
    container_name: $APP_NAME
    image: docker.isaacscience.org/isaac-cs-app:$APP_VERSION
    restart: unless-stopped
    networks:
      default:
        aliases:
          - cs-app-$ENV
  $API_NAME:
    container_name: $API_NAME
    image: docker.isaacscience.org/isaac-api:$API_VERSION
    restart: unless-stopped
    extra_hosts:
      - local-smtp:$LOCAL_SMTP
    external_links:
      - cs-pg-live:postgres
      - cs-elasticsearch-live:elasticsearch
    environment:
      - SEGUE_CONFIG_LOCATION=/local/data/conf/segue-config.properties
    volumes:
      - /local/data/m2:/root/.m2:rw
      - /local/data/isaac-config/cs/segue-config.$ENV.properties:/local/data/conf/segue-config.properties:ro
      - /local/data/cs-content:/local/data/cs-content:rw
      - /local/data/keys:/local/data/keys:ro
      - /local/data/school_list_2019.csv:/local/data/school_list_2019.csv:ro
      - /var/log/isaac/cs-$ENV:/isaac-logs:rw
    networks:
      default:
        aliases:
          - cs-api-$ENV-any
    logging:
      driver: journald
      options:
        tag: isaac-cs-api-$ENV
networks:
  default:
    external:
      name: isaac
EOF

exit 0
