#!/bin/bash

# Fail on error, so this script can be chained safely:
set -e

# Need at least three args and the first argument to be the site:
if [ $# -lt 3 ] || ! { [ $1 = "ada" ] || [ $1 = "phy" ] || [ $1 = "sci" ]; }; then
  echo "Usage: compose-etl [ada|phy|sci] [APP_VERSION] [DOCKER_ARGS]..."
  echo "Note this is the app version and not the API version!"
  exit 1
fi

DOCKER_REPO=ghcr.io/isaacphysics

# Extract args:
SITE=$1
SUBJECT=$1
APP_VERSION=$2
ENV=live
# We're done with the first two args. The remainder will be passed to docker compose:
shift 2

# Whilst things are shared, some "sci" things are named "phy":
if [ "$SITE" == "sci" ]; then
  SUBJECT="phy"
fi

# Use the app image to find the correct API version to use:
if [ $1 = "create" ] || [ $1 = "pull" ] || [ $1 = "push" ] || [ $1 = "run" ] || [ $1 = "start" ] || [ $1 = "up" ]; then
  # This will cause new containers or should update containers, so pull newer images if possible:
  docker pull $DOCKER_REPO/isaac-$SUBJECT-app:$APP_VERSION
  API_VERSION=$(docker inspect -f '{{.Config.Labels.apiVersion}}' $DOCKER_REPO/isaac-$SUBJECT-app:$APP_VERSION)
  docker pull $DOCKER_REPO/isaac-etl:$API_VERSION

elif [ $1 = "down" ] || [ $1 = "stop" ] || [ $1 = "restart" ] || [ $1 = "exec" ] || [ $1 = "config" ] || [ $1 = "logs" ] || [ $1 = "kill" ] || [ $1 = "ps" ]; then
  # This affects existing containers, so don't pull newer images:
  API_VERSION=$(docker inspect -f '{{.Config.Labels.apiVersion}}' $DOCKER_REPO/isaac-$SUBJECT-app:$APP_VERSION)

else
  # This might not be a docker compose operation. If it is, it could be added above to the correct branch.
  echo "Error: Unsupported docker compose operation '$1'!"
  exit 1
fi

# Ensure we actually _have_ an API_VERSION before we continue, though the "set -e" might avoid this:
if [ -z $API_VERSION ]; then
  echo "Error: Cannot extract API version from APP image!"
  exit 1
fi

ETL_NAME=$SITE-etl-$API_VERSION
ES_CONTAINER=$SITE-elasticsearch-v8-live

# The content repo is named differently for both sites in a non-standard way:
if [ "$SITE" == "ada" ]; then
  CONTENT_REPO="ada-content"
elif [ "$SITE" == "phy" ]; then
  CONTENT_REPO="rutherford-content"
fi

docker compose -p dc-$SITE-etl -f - $@ << EOF
services:
  $SITE-etl:
    container_name: $ETL_NAME
    image: $DOCKER_REPO/isaac-etl:$API_VERSION
    environment:
      - SEGUE_CONFIG_LOCATION=/local/data/config/segue-config.dec.yaml
      - JAVA_OPTIONS=-Dlog.path=/isaac-logs -Dsegue.version=$API_VERSION -Djetty.port=8090
    volumes:
      - /local/data/m2:/root/.m2:rw
      - /local/data/isaac-sops-config-decrypted/$ENV/$SITE:/local/data/config:ro
      - /local/data/isaac-config/$SUBJECT/content_indices.properties:/local/data/conf/content_indices.properties:rw
      - /local/data/$CONTENT_REPO:/local/data/$CONTENT_REPO:rw
      - /var/log/isaac/$SITE-etl:/isaac-logs:rw
    external_links:
      - $ES_CONTAINER:elasticsearch
    networks:
      default:
        aliases:
          - $SITE-etl
          - $SUBJECT-etl
    logging:
      driver: journald
      options:
        tag: $SITE-isaac-etl
networks:
  default:
    name: isaac
    external: true
EOF

exit 0

