FROM cypress/browsers

WORKDIR /tests

COPY ./package.json .
COPY ./yarn.lock .
COPY ./tsconfig.json .
COPY ./cypress.config.ts .
COPY ./cypress ./cypress
COPY ./config ./config
COPY ./public ./public

RUN yarn install

ENTRYPOINT ["yarn", "cypress", "run", "--component"]

