FROM ubuntu:latest

RUN apt-get update
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y ca-certificates curl openssl git apt-transport-https gnupg-agent software-properties-common

# Install Node
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -yy nodejs

# Install Yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install -yy --no-install-recommends yarn


# Install Docker

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN add-apt-repository \
        "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) \
        stable"
RUN DEBIAN_FRONTEND="noninteractive" apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io

COPY ./build.sh /build.sh

CMD ["./build.sh"]
