ARG BUILD_TARGET="build-phy"

FROM node:19.2.0-buster AS builder
ARG BUILD_TARGET

RUN mkdir /build
WORKDIR /build

COPY package.json /build
COPY yarn.lock /build
RUN yarn install --frozen-lockfile

COPY . /build
RUN yarn $BUILD_TARGET

FROM nginx:stable
ARG BUILD_TARGET

COPY --from=builder /build/$BUILD_TARGET/ /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
