export default {
  section1: {
    header: {
      section: [
        "Calling all computer science fans! Isaac Computer Science, ran by the National Centre for Computing Education (NCCE), is hosting a national competition that challenges students to imagine, design, and pitch a groundbreaking new product for the Internet of Everything.",
        " The competition is a fantastic opportunity for students to apply their knowledge to real-world ideas.",
      ],
    },
    note: {
      heading: "Please note:",
      entryDetails:
        "Competition entries open in January and last two months. Students will be able to submit their entries until 28 March 16:00. Follow our",
      callToAction: "accounts for updates.",
      xLink: "https://x.com/isaaccompsci",
      facebookLink: "https://www.facebook.com/IsaacComputerScience",
    },
  },
  internetOfEverything: {
    ioe: {
      title: "What is the Internet of Everything?",
      section: [
        "Imagine a world where everything around you is connected to the internet. Not just your phone or computer, but your watch, your shoes, your fridge, even your toothbrush! This is what we call the Internet of Everything.",
        "The IoE is like a giant invisible web that connects all things, people, data, and processes. It’s like a big team where everyone and everything works together, sharing information and making decisions.",
        "The IoE is made up of four main parts: people, things, data, and processes. When these parts work together, they can make our lives easier, safer, and more enjoyable.",
      ],
    },
    examples: {
      title: "Real-life examples of IoE include:",
      section: [
        "smart homes: imagine your alarm clock wakes you up and then automatically tells your coffee maker to start brewing coffee",
        "wearable devices: devices like smartwatches can monitor your health, track your location if you’re lost, and even let you make phone calls or send messages",
        "smart cities: streetlights that turn off when it is light outside, or traffic lights that adjust based on road conditions",
        "connected cars: cars can communicate with each other to avoid accidents. They can also tell you when they need repairs or even call for help if there’s an emergency",
      ],
    },
    testamonial: {
      text: "The Internet of Everything isn’t just about smart devices; it’s about connecting everything to make life easier, safer, and more enjoyable. It’s like a superpower that lets us make objects work together — but we must use this power responsibly and safely.",
    },
  },
  section3: {
    howItWorks: {
      title: "How does it work?",
      steps: [
        "1. Students need to ask their teacher to participate",
        "2. Students and teachers create or log in to an account",
        "3. Attend our Q&A sessions for tips and tricks on entries (coming soon)",
        "4. Boost your knowledge with our Student Boosters and Gameboards",
        "5. Submit your entry! The finalists will be selected and invited to a final in Birmingham on 19 May.",
      ],
    },
    whyJoin: {
      title: "Why join the competition?",
      description: "Participating in this competition will allow students to:",
      benefits: [
        "a. network with industry leaders: meet professionals, gain insights into potential career paths, and build connections",
        "b. enhance their computer science knowledge: revise for mock exams through interactive gameboards and practical applications",
        "c. showcase their talent: stand out on future university or job applications and earn the title of an IoE innovator",
      ],
    },
    eligibility: {
      title: "Who can join?",
      description:
        "This competition encourages teamwork, allowing groups of up to 4 students or individual entries with teacher support.",
      requirements:
        "Eligible participants must be in Year 9, 10, or 11 during the 2024/2025 academic year and attend a state-funded school in England; private, independent, and home-educated students are not eligible.",
    },
    prizes: {
      title: "🏆 The prizes",
      description: "Finalists from each region will participate in exclusive partner events, which may include:",
      prizeList: [
        "£50 Amazon gift vouchers",
        "industry tours with partners such as Siemens and Arcadis",
        "a Royal Albert Hall box for a show of your choice",
        "Isaac Computer Science merchandise to support students",
      ],
    },
    timeline: {
      title: "Competition Timeline",
      content:
        "Save the 2024/25 dates in your calendar and plan time for you or your team to develop your IoE idea before applications close.",
      entries: [
        { event: "Entries open", date: "January" },
        { event: "Entries close", date: "28 March 16:00" },
        { event: "Finalist selected", date: "April" },
        { event: "The final", date: "19 May" },
      ],
    },
  },
  accordion: {
    projectIdeas: {
      title: "Project ideas to get started",
      section: [
        "There are endless possibilities! However, we know how hard it is to start with a blank page. Here are a few ideas to get you started:",
        [
          "develop an app or game that promotes healthy sleep habits",
          "design a website to educate youth on mobile device cybersecurity",
          "propose an Internet of Everything device concept that helps keep public spaces clean",
        ],
        "These ideas are only the beginning: we can’t wait to see what you think of!",
      ],
    },
    availableSupport: {
      title: "Available support",
      section: [
        "We have a range of topics to help out with your design of your IoE device. Take a look:",
        [
          "Embedded Systems",
          "The processor",
          "Factors affecting processor performance",
          "RAM: Main memory",
          "Wired and Wireless networks",
          "Cybersecurity: Network threats",
          "Legislation",
          "Impacts of technology",
        ],
        "Our industry partners are also here to help! Siemens have offered to help with their Games Arcade, and are offering free software licenses for SolidEdge – CAD design to get you started.",
      ],
    },
    video: {
      title: "Video entry requirements",
      section: [
        "Video content requirements:",
        [
          "The video must introduce the team or an individual and give an overview of the project outlining the global problem addressed by the IoE device. Introduce yourself using the first names only and the title of your video, if required. Think about how you can stand out and be creative!",
          "The video must describe the device and its features showcasing a design or prototype.",
          "The video must explain how the IoE device will improve lives globally.",
          "If a group Entry is submitted, the video must discuss the collaboration skills and methods used when working on the project. In case of an individual Entry, a student must explain their approach when working on the project.",
        ],
        "Video technical requirements:",
        [
          "The video must be recorded in a landscape mode if possible.",
          "The video must have clear audio and video with good lighting.",
          "The video must be in one of the accepted formats such as MP4, MOV, AVI.",
          "The video must not include inappropriate content, copyrighted music, or videos.",
          "If using a PowerPoint presentation for the video, a Student(s) must record a voiceover.",
          "Name your file with your group name and entry title. For example: NameofGroup_CompetitionEntry.mp4.",
          "The video and any additional supporting materials must be uploaded to a cloud storage folder (e.g., Google Drive, Dropbox) ensuring that it is accessible by the Organiser for the duration of the Competition.",
        ],
        "Supporting Documents",
        [
          "While not mandatory, supporting documents can enhance your submission. Consider including:",
          [
            "Diagrams or sketches of your device.",
            "A brief written summary of your project.",
            "Evidence of research or data that supports your concept.",
            "Reflections on collaboration and teamwork.",
          ],
        ],
        "Tips for Success",
        [
          "Identify a Global Challenge: Consider issues like climate change, health crises, education gaps, or social isolation.",
          "Innovative Design: Think creatively about how your device can uniquely address the problem.",
          "Collaboration Skills: Highlight how you worked together as a team, including communication, conflict resolution, and decision-making processes.",
          "Practice Your Presentation: Rehearse your video to ensure clarity and confidence.",
        ],
        "Resources",
        [
          "Workshops: Attend any available workshops or information sessions to help refine your ideas.",
          "Online Resources: Explore websites and articles on IoE technology, design thinking, and teamwork strategies.",
          "Teacher Support: Work closely with your teacher to guide your project and provide insights.",
        ],
        "If you have any questions or run into problems, contact <a href='https://isaaccomputerscience.org/contact?examBoard=all&stage=all'>here</a>. Good luck — we can’t wait to see your video!",
      ],
    },
    groupEntry: {
      title: "How to create a group and submit your entry",
      section: [
        "How to create a group:",
        [
          "Only users with a teacher account can create a group. If you don’t have a teacher account, you can request one when signing up on the platform or through your student account settings. We aim to process all requests as quickly as possible, but it may take up to 5 working days. More information about teacher accounts <a href = 'https://isaaccomputerscience.org/support/teacher/general?amp;stage=all&examBoard=all&stage=all'>here</a>.",
          "Click on Teachers on the menu bar, then click on <a href = 'https://isaaccomputerscience.org/groups?examBoard=aqa&stage=a_level'>Manage groups</a>",
          [
            "Enter a name for your new group. The group name will be shared with your students, so make it useful for them too.",
            "For a student group entry, the Competition requires each group to consist of 2 to 4 students. If a student is working on the application individually, a teacher must create a separate group for them.",
            "Click on Create.",
          ],
        ],
        "How to invite students to join a group",
        [
          "To invite your students to join a group, click on the 'Invite Users' button on the Manage groups page.",
          "Choose between a URL or an authentication code to share with the students.",
          "Find details about <a href='https://isaaccomputerscience.org/support/student/homework?examBoard=aqa&stage=a_level'>how students join groups here</a>. When students use the URL or code, they will be shown your first initial, last name, and email address, and they’ll be asked to confirm they want to share their progress with you.",
          "We recommend that you access your <a href='https://isaaccomputerscience.org/groups?examBoard=aqa&stage=a_level'>Manage groups</a> page when students first join your group to make sure that they’ve all verified their account email addresses before they log out.",
        ],
        "How to submit a Competition entry",
        [
          "Teachers are responsible for submitting the work of students on their behalf.",
          "Go to the entry form and enter your full first and last name. If needed, you can update your name in your account settings.",
          "In the URL box, provide a link to the cloud storage where your video and any supporting materials are saved. Ensure the link is accessible to the Organiser by setting the correct permissions (e.g., open to anyone with the link).",
          "From the dropdown, select a group that you created for this competition",
        ],
        "If you have any questions or run into problems, contact <a href='https://isaaccomputerscience.org/contact?examBoard=all&stage=all'>here</a>.",
      ],
    },
    industry: {
      title: "Industry Partners",
      section: [
        "A big thank you to all of our industry partners! These include:",
        [
          "The British Computer Society, branded BCS, The Chartered Institute for IT",
          "Arcadis",
          "Cisco",
          "Kainos",
          "Reed",
          "Siemens",
          "TC",
        ],
        "",
        "A big thank you to Birmingham City University for giving us space to host the finals. The University has offered continuous support throughout the competition, and we are excited to partner with them and be a part of the Innovation Fest 19th May - 23rd May 2025.",
      ],
    },
    termsAndConditions: {
      title: "Terms and Conditions – National Computing Competition 2024/25",
      section: [
        "The National Computing Competition (Competition) is run by the Department for Education’s National Centre for Computing Education (run by STEM Learning Limited (company number 05081097) hosted on the Isaac Computer Science platform (“Organiser”, “We” “Us” and “Our”), in partnership with the industry companies. “You” and “Your” refer to the Teacher(s) entering the Competition on behalf of a group of students or an individual student who meets the eligibility requirements.",
        "1.0 Introduction",
        [
          "1.1. By entering the Competition, you agree to abide by these Terms and Conditions. We reserve the right to refuse entry or award the prize to anyone in breach of these Terms and Conditions.",
          "1.2. “Student(s)” refers to the individual(s) in Years 9, 10, or 11, studying at a state-funded school in England and whose project is being submitted by teachers to enter the Competition.",
          "1.3, “Teacher(s)” refers to the individual(s) aged 18 or over who are employed by a state-funded school in England. They will be responsible for submitting the work of students on their behalf and communicating with the Organiser.",
          "1.3. “Entry” refers to the Internet of Everything (IoE) product concept or prototype submission by the Student(s) in the format of a video presentation.",
          "1.4. “Prize” refers to the awards outlined on the Isaac Computer Science website, which may include a participation certificate, Amazon gift vouchers, industry tours, and other partner-sponsored rewards.",
          "1.5. “Finalist(s)” refers to the Student(s) selected to participate in the regional finals.",
          "1.6. “Winner(s)” refers to the Student(s) who wins the Competition.",
        ],
        "2.0 Eligibility",
        [
          "2.1. The Competition is open to students in Years 9, 10, or 11, attending state-funded schools in England. Groups must comprise of between 2 and 4 Students, assisted by a teacher. Submissions by individual students are permitted. For group entries, team members must all go to the same school but can be in different classes, forms, or years.",
          "2.2. Students attending private, independent, or home-education settings are not eligible to participate in the Competition.",
          "2.3. Each team should have a Teacher responsible for monitoring the team’s progress, available to offer help and advice, and acting as the point-of-contact between the Organiser and the Student(s) team. The Organiser will not be able to communicate directly with the Student(s).",
          "2.4. There is no entry fee, and no purchase is necessary to enter this Competition.",
          "2.5. Entries must be original and the sole work of the Student(s) participating.",
          "2.6. Entries must not infringe the intellectual property of any third party.",
          "2.7. By submitting an entry, you confirm that the Student(s) meet the eligibility requirements.",
          "2.8. By entering this Competition, you confirm that You have received parental consent of the Student(s) whose entry is entered into the Competition, and verbal assent from the Student(s) to enter the Competition under these Terms and Conditions.",
        ],
        "3.0 How to Enter",
        [
          "3.1. To enter the Competition:",
          [
            "3.1.1. Teacher(s) and Student(s) register on the Isaac Computer Science platform or log in their existing account(s).",
            "3.1.2. Teacher creates a group(s) on the Isaac Computer Science platform connecting the accounts of the Student(s) that are making an entry.",
            "3.1.3. Student(s) works on a product concept or prototype demonstrating an IoE idea in the video format adhering to specified Entry requirements and Entry deadlines.",
            "3.1.4. Teacher(s) submits a product concept or prototype demonstrating an IoE idea in the video format on behalf of a Student(s) or a group(s) of Students on the Isaac Computer Science platform.",
          ],
          "3.2. All entries must be received by 4 pm on 28 March 2025. Any entries received after this will not be considered.",
          "3.3. Only one entry per group or individual is allowed. Student(s) may submit one entry as an individual and one as part of a group, provided that each entry is a unique and original work with no overlap in content or materials between the two submissions.",
          "3.4. Teacher(s) or mentors must supervise each entry.",
          "3.5. Teacher(s) must ensure that all entries are in compliance with their school’s safeguarding policy.",
        ],
        "4.0 Entry Requirements",
        [
          "4.1. Student(s) must design a concept for an Internet of Everything (IoE) device aimed at improving the lives of a global society. Each entry must showcase the concept, including the design or prototype, along with any supporting documents if desired.",
          "4.2. The Entry must be submitted in video format of up to 5 minutes long. Any videos longer than 5 minutes will not be reviewed.",
          "4.3. Video content requirements:",
          [
            "4.3.1. The video must introduce the team or an individual and give an overview of the project outlining the global problem addressed by the IoE device.",
            "4.3.2. The video must describe the device and its features showcasing a design or prototype.",
            "4.3.3. The video must explain how the IoE device will improve lives globally.",
            "4.3.4. If a group Entry is submitted, the video must discuss the collaboration skills and methods used when working on the project. In case of an individual Entry, a Student must explain their approach when working on the project.",
          ],
          "4.4. Student(s) are encouraged to include additional materials to support their video submission such as:",
          [
            "- Diagrams, sketches, or visual representations of the IoE device.",
            "- Concise written summary of the project.",
            "- Research data or evidence supporting the feasibility and impact of the concept.",
            "- Reflections on collaboration and teamwork during the project’s development.",
          ],
          "4.5. Video technical requirements:",
          [
            "4.5.1. The video must be recorded in a landscape mode if possible.",
            "4.5.2. The video must have clear audio and video with good lighting.",
            "4.5.3. The video must be in one of the accepted formats such as MP4, MOV, AVI.",
            "4.5.4. The video must not include inappropriate content, copyrighted music, or videos.",
            "4.5.5. If using a PowerPoint presentation for the video, a Student(s) must record a voiceover.",
            "4.5.6. The video and any additional supporting materials must be uploaded to a cloud storage folder (e.g., Google Drive, Dropbox) ensuring that it is accessible by the Organiser for the duration of the Competition.",
          ],
          "4.6. We do not accept entries:",
          [
            "- Automatically generated by computer or completed by third parties.",
            "- Without a video that is relevant to the topic and clearly narrated.",
          ],
        ],
        "5.0 Judging and Selection of Finalists",
        [
          "5.1. Finalists will be chosen from the highest scoring submissions against the following assessment criteria:",
          [
            "1. Creativity and Originality: (20 points) Innovativeness of the concept and uniqueness of the idea",
            "2. Practicality and Feasibility: (20 points) Realistic implementation and technical feasibility. ",
            "3. Impact on Society: (30 points) Potential to improve lives globally and alignment with the theme.",
            "4. Presentation Quality: (30 points) Clarity and organization and Engagement and communication skills.",
          ],
          "5.2. Finalists will be selected by a judging panel comprising of the Organiser representatives and industry professionals. The judges’ decisions are final, and no appeals can be made regarding the results.",
          "5.3. Finalists will be invited to present their projects at the final event. The final event is proposed to be held on 19 May 2025 in Birmingham. The exact details of the final will be shared with the Finalists.",
          "5.4. Finalists judged to be the Winners of the competition will receive prizes, which may include a participation certificate, Amazon gift vouchers, industry tours, and other partner-sponsored rewards.",
          "5.5. If Student(s) are selected as Finalist(s), Teacher must confirm participation in the final within one week of notification. In the event of delayed response or inability to attend, We reserve the right to offer the place to an alternative entry.",
          "5.6. We will publish the names of the winning school(s) and project details on Our websites and social media.",
        ],
        "6.0 Final",
        [
          "6.1. The final will be a one-day event consisting of presentations, talks and workshops from industry representatives, as well as final presentations of the IoE device concepts and prototypes from the Competition Finalists.",
          "6.2. Finalists of the Competition will be invited to a final event to present a concept or prototype of their IoE device in person. Finalists will be required to submit a device presentation ahead of the final. The exact date and location to be confirmed to the Finalists later.",
          "6.3. The Winners will be decided on by a judging panel appointed by the Organiser and announced during the final event.",
          "6.4. The school of the Finalist(s) will be responsible for travel arrangements and will pay for transport to and from the final event the student(s) was invited to. Provision may be available for those who find difficulties in reaching the final.",
          "6.5. Student(s) must be accompanied by school staff who must hold a valid DBS certificate and obtain consent forms from the 'students’ parents or guardians.",
        ],
        "7.0 Prizes",
        [
          "7.1. All Finalists will receive a certificate of participation, and all Winners will receive a certificate of achievement for winning the Competition.",
          "7.2. Additional Prizes for Winners may include, but subject to change:",
          [
            "- £50 Amazon gift vouchers",
            "- industry tours with partners such as Siemens and Arcadis",
            "- A Royal Albert Hall box for a show of your choice",
            "- Isaac Computer Science notebook, pen, water bottle and stickers",
          ],
          "7.3. Prizes will be shared between the students in a group.",
          "7.4. The Winner accepts and agrees that:",
          [
            "7.4.1. The Prize must be taken as stated, it is non-transferable, and cannot be deferred, exchanged or redeemed for its value.",
            "7.4.2. No alternative to the Prize will be available.",
            "7.4.3. Our decision is final and binding and no correspondence will be entered into about it.",
            "7.4.4. All Prizes will be given to the Teacher who submitted the winning Entry and it is their responsibility to ensure the Prize is given to the student(s).",
          ],
        ],
        "8. Rights and Permissions",
        [
          "8.1. By entering, you grant the Organiser and its partners a non-exclusive, perpetual, royalty-free license to use the entry material for promotional purposes of the Competition.",
          "8.2. Finalists and Winners may be asked to participate in additional promotional activities, including media coverage.",
          "8.2.1. We may announce the Winners via: STEM Learning, National Centre for Computing Education and Isaac Computer Science websites and social media channels, email correspondence, and other relevant third parties involved in the Competition.",
          "8.3. Any Entry found to have infringed third-party intellectual property rights or to have been automatically generated by computer will be withdrawn from the Competition.",
          "8.4. The intellectual property rights of the submitted work remain with the Student(s) who submitted the Entry.",
          "8.5. Student(s) taking part in the Competition agree to allow the Organiser and its partners to retain the exclusive right to use their entry online, in marketing, media and public display to promote the Competition free of charge and with no time limit.",
          "8.6. Entrants and participating schools will be credited where feasible, but Isaac Computer Science reserves the right to use the submissions without attribution if necessary.",
          "8.7. By entering, you confirm that the submission is original and does not infringe upon any third-party intellectual property rights.",
        ],
        "9. Liability",
        [
          "9.1. We are not responsible for any technical errors or other issues that may prevent entries from being submitted or considered.",
          "9.2. We do not accept responsibility for system errors or other issues that may result in disruption to, lost, delayed or not received entries, winner notifications or prizes.",
          "9.3. If the Competition cannot proceed due to unforeseen circumstances, We reserve the right to amend, suspend, or cancel it.",
          "9.4. If an act, omission, event or circumstance occurs which are beyond Our reasonable control and which prevents Us from complying with these terms and conditions, We will not be liable for any failure to perform or delay in performing Our obligation.",
          "9.5. We shall not be liable for any costs associated with participating in the Competition.",
          "9.6. We may review and revise these terms and conditions at any time without giving prior notice.",
        ],
        "10. Data Protection",
        [
          "10.1. We will only process personal data in accordance with Our <a href='https://isaaccomputerscience.org/privacy?examBoard=all&stage=all'>Privacy Policy</a> and Competition terms.",
          "10.2. Student(s)’s first names and school names may be used in publicity associated with the Competition.",
        ],
        "11. General",
        [
          "11.1. If there is any reason to believe that there has been a breach of these terms and conditions, We may, at Our sole discretion, reserve the right to exclude You from participating in the Competition.",
          "11.2. We reserve the right to hold void, suspend, cancel, or amend the Competition and/or Prize where it becomes necessary to do so.",
          "11.3. These Terms and Conditions are governed by English law, and any disputes will be subject to the jurisdiction of the English courts.",
        ],
      ],
    },
  },
};
