name: Publish Docker Image

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push cs Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          file: Dockerfile-react
          context: .
          push: true
          build-args: |
            BUILD_TARGET="build-cs"
          tags: ghcr.io/${{ github.repository }}-cs
      - name: Build and push cs-renderer Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          file: Dockerfile-react
          context: .
          push: true
          build-args: |
            BUILD_TARGET="build-cs-renderer"
          tags: ghcr.io/${{ github.repository }}-cs-renderer
      - name: Build and push phy Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          file: Dockerfile-react
          context: .
          push: true
          build-args: |
            BUILD_TARGET="build-phy"
          tags: ghcr.io/${{ github.repository }}-phy
      - name: Build and push phy-renderer Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          file: Dockerfile-react
          context: .
          push: true
          build-args: |
            BUILD_TARGET="build-phy-renderer"
          tags: ghcr.io/${{ github.repository }}-phy-renderer
